/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    Checkbox: typeof import('./src/components/FormElements/Checkbox.vue')['default']
    CustomDefault: typeof import('./src/components/FormElements/CustomDefault.vue')['default']
    CustomInput: typeof import('./src/components/FormElements/__tests__/Views/CustomInput.vue')['default']
    Error: typeof import('./src/components/FormElements/Error.vue')['default']
    Form: typeof import('./src/components/FormElements/Form.vue')['default']
    FormTest: typeof import('./src/components/FormElements/__tests__/Views/FormTest.vue')['default']
    Input: typeof import('./src/components/FormElements/Input.vue')['default']
    InputText: typeof import('@vue-formify/primevue')['InputText']
    Radio: typeof import('./src/components/FormElements/Radio.vue')['default']
    ToggleButton: typeof import('@vue-formify/primevue')['ToggleButton']
  }
}
