name: Oxlint and Vitest

on:
 pull_request:
  branches: [master, main]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
        node-version: 20
  - run: npm i
  - name: Run oxlint
    run: npm run oxl:lint
  - name: Run vitest
    run: npx vitest --environment jsdom run
